######################## default configuration ####################
baseURL = "https://hossein.blog"
languageCode = "en-us"
title = "Hossein's Blog | Blogging Around"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = ""
enableEmoji = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"

  
############################## navigation ###############################
[menu]
  
  # main menu
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 1
  
  [[menu.main]]
  name = "Post"
  URL = "blog"
  weight = 2

  # footer menu
  [[menu.footer]]
  name = "About"
  URL = "about"
  weight = 1
  
  [[menu.footer]]
  name = "Post"
  URL = "blog"
  weight = 2


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "I'm Hossein. A web developer who is curious about everything. Here is are my sharing about everything I face or explore. I will write articles about general topics, programming, technology, and data science."
author = "Hossein Shahsahebi"
# Google Analitycs
googleAnalitycsID = "UA-161962212-1"
# Contact Information
mobile = "+601123209399"
mobile_enabled = false
email_text = "me [at] hossein.blog"
email_link = "me@hossein.blog"
email_enabled = true
location = "Kuala Lumpur, Malaysia"
location_enabled = true
# copyright
copyright = "| Hossein's blog, developed by me using [Hugo](https://hugo.com) & [Themefisher](https://themefisher.com) |"

  # Preloader
  [params.preloader]
  enable = false
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = true

############################ news letter ########################
[params.newsletter]
enable = false
title = "Join My Newsletter"
content = ""

############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/hossein.blog"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/hossein_blog"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "https://www.instagram.com/hossein.blog"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/hshahsahebi"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/in/hshahsahebi/"